//
// Created by cucaracha on 22.04.18.
//

#ifndef MININGSIMULATORGAMESERVER_CONFIGCONST_H
#define MININGSIMULATORGAMESERVER_CONFIGCONST_H

const TIME_MILSEC tACCUM_ONE_ENERGY = 30;
const UINT32 nMAX_ENERGY = 10;

#endif //MININGSIMULATORGAMESERVER_CONFIGCONST_H